settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: /Users/jdevloo001/go/src/github.com/Jensdevloo/golang-rpi-gpio-toggle
  path: /Users/jdevloo001/go/src/github.com/Jensdevloo/golang-rpi-gpio-toggle
  env:
    DEBUG: "true"
    PORT: "8080"
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
